org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=solardimensionaddon
mod_name=Create Solar Dimension Efficiency
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.kazeshukufuku.solardimensionaddon
mod_authors=KazeShukufuku
mod_description=Adds dimension-specific efficiency multipliers for Create: Solar Powered solar panel output.

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47.4.0,)
loader_version_range=[47,)
